
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
    - role: endpoints
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
    - role: node
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
    - role: pod
  - job_name: 'langgraph-agent'
    kubernetes_sd_configs:
    - role: service
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_label_app]
      regex: 'langgraph-agent'
      action: keep
